namespace: default

replicaCount: 1

appLabel: nginx-custom

image:
  repository: my-nginx-custom-org1
  tag: "1.0"

container:
  name: nginx-custom
  port: 80

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

volume:
  mountPath: /usr/share/nginx/html/files
  claimName: nginx

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
namespace: default

ingress:
  name: org1-server-ingress
  className: nginx
  host: org1.test
  path: /
  pathType: Prefix
  forceSslRedirect: "false"

service:
  port: 80
  targetPort: 80
