namespace: default

replicaCount: 1
appLabel: nginx-custom-org2

image:
  repository: my-nginx-custom-org2
  tag: "1.0"

container:
  name: nginx-custom-org2
  port: 80

service:
  name: org2-server
  port: 80
  targetPort: 80
  portName: http

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

volume:
  mountPath: /usr/share/nginx/html/files
  claimName: nginx

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

ingress:
  name: org2-server-ingress
  className: nginx
  host: org2.test
  path: /
  pathType: Prefix
  forceSslRedirect: "false"
