wordpressUsername: admin
wordpressPassword: password123
wordpressEmail: admin@example.com
wordpressBlogName: "My Test Site with Argo"
wordpressBlogDescription: "Testing Argo deployments"

mariadb:
  auth:
    rootPassword: rootpass123

ingress:
  enabled: true
  ingressClassName: nginx   # 👈 must match ingress controller
  hostname: argocd.test.com
  path: /
  pathType: Prefix

persistence:
  enabled: true
  size: 10Gi
