apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-org1-prod
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: oci://registry-1.docker.io/bitnamicharts/nginx 
    targetRevision: 15.9.0
    helm:
      valuesObject:
        some-value: foo
  destination:
    server: https://kubernetes.default.svc
    namespace: org1-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
